import React,{useState} from 'react';
import {ArrowRight,LockKeyhole,Phone,ShieldCheck,ChevronDown,CheckCircle2} from 'lucide-react';
import {User,Campaign,CampaignContext} from '../types';
import {authenticate,refreshUsersFromGoogleSheets,purgeAndResetEverything} from '../utils/storage';
import {getCampaignsForUser} from '../utils/merchantCampaign';
interface Props{onLoginSuccess:(user:User,campaign?:CampaignContext)=>void}
const context=(c?:Campaign|null):CampaignContext=>c?.code==='youth-f2f'?'youth-f2f':c?.campaign_type==='brand_ambassador'?'merchant-educational':'rida-installation';
export const LoginScreen:React.FC<Props>=({onLoginSuccess})=>{
 const [phone,setPhone]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[pending,setPending]=useState<User|null>(null),[campaigns,setCampaigns]=useState<Campaign[]>([]),[selected,setSelected]=useState(''),[campaignMenu,setCampaignMenu]=useState(false);
 const finish=(u:User,c?:Campaign|null)=>onLoginSuccess(u,context(c));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{await refreshUsersFromGoogleSheets();const r=authenticate(phone.trim(),password.trim());if(!r.success||!r.user){setError(r.message||'Identifiants incorrects.');return}if(r.user.role==='agent'){try{const cs=await getCampaignsForUser(r.user.id);if(cs.length>1){setPending(r.user);setCampaigns(cs);setSelected(cs[0].id);return}finish(r.user,cs[0]);}catch{finish(r.user)}}else finish(r.user)}catch{const r=authenticate(phone.trim(),password.trim());if(r.success&&r.user)finish(r.user);else setError(r.message||'Connexion impossible.')}finally{setLoading(false)}};
 if(pending)return <div className="login-v2"><div className="login-grid"/><div className="login-card"><div className="login-mark">R</div><span className="login-label">ESPACE DE TRAVAIL</span><h1>Choisir votre campagne</h1><p>Bonjour {pending.name.split(' ')[0]}. Sélectionnez l’espace opérationnel à ouvrir.</p><div className="rida-picker"><button type="button" className="rida-picker-trigger" onClick={()=>setCampaignMenu(!campaignMenu)} aria-haspopup="listbox" aria-expanded={campaignMenu}><span>{campaigns.find(c=>c.id===selected)?.name||'Choisir une campagne'}</span><ChevronDown size={18}/></button>{campaignMenu&&<div className="rida-picker-menu" role="listbox">{campaigns.map(c=><button key={c.id} type="button" className={selected===c.id?'selected':''} onClick={()=>{setSelected(c.id);setCampaignMenu(false)}}><span>{c.name}</span>{selected===c.id&&<CheckCircle2 size={16}/>}</button>)}</div>}</div><button className="login-submit" onClick={()=>finish(pending,campaigns.find(c=>c.id===selected))}>Continuer <ArrowRight size={18}/></button><button className="login-back" onClick={()=>setPending(null)}>Utiliser un autre compte</button></div></div>;
 return <div className="login-v2"><div className="login-grid"/><div className="login-layout"><div className="login-intro"><div className="login-brand"><div className="login-mark">R</div><div><strong>RIDA<span>OPS</span></strong><small>FIELD OPERATIONS</small></div></div><div className="login-copy"><span>RIDA · LUBUMBASHI</span><h1>Le terrain,<br/><em>maîtrisé.</em></h1><p>Une plateforme unique pour organiser les équipes, sécuriser les pointages et transformer l’activité terrain en données exploitables.</p></div></div><div className="login-card"><div className="login-card-head"><span className="login-label">ACCÈS</span><ShieldCheck size={20}/></div><h2>Bienvenue</h2><p>Ouvrez votre espace opérationnel.</p><form onSubmit={submit}><label><span><Phone size={15}/> Téléphone</span><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="081 XXX XX XX" autoComplete="username" required/></label><label><span><LockKeyhole size={15}/> Clé d’accès</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Votre mot de passe" autoComplete="current-password" required/></label>{error&&<div className="login-error">{error}</div>}<button className="login-submit" disabled={loading}>{loading?'VÉRIFICATION…':'OUVRIR MON ESPACE'}<ArrowRight size={18}/></button></form><div className="login-foot">Accès réservé aux membres autorisés de la campagne RIDA.</div></div></div><button className="login-reset" aria-label="Réinitialiser les données locales" title="Réinitialiser les données locales" onClick={()=>{if(window.confirm('Réinitialiser les données locales ?')){purgeAndResetEverything();location.reload()}}}>↻</button></div>;
};